export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAILS = "ADMIN_LOGIN_FAILS";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";

export const ADMIN_VIEW_ORDERS_REQUEST = "ADMIN_VIEW_ORDERS_REQUEST";
export const ADMIN_VIEW_ORDERS_SUCCESS = "ADMIN_VIEW_ORDERS_SUCCESS";
export const ADMIN_VIEW_ORDERS_FAILS = "ADMIN_VIEW_ORDERS_FAILS";
export const ADMIN_VIEW_ORDERS_RESET = "ADMIN_VIEW_ORDERS_RESET";
